slug: aws-infra
title: AWS & インフラ構築
description: ""
version: 0.1.0
created_at: 2026-05-29
updated_at: 2026-05-29
authors: []
visibility: private # private | shared | unlisted | public
shared_with: []
unlisted_token: null
search_indexable: false
allow_fork: false
tags: []
contains_local_sources: false
curriculum_order:
  - aws-basics
  - terraform-aws
